### ISSUE TITLE
Error when creating new customer on odoo 8

### ISSUE THREAD

**Issue by tboulogne** [akretion/ooor#121]
Hello and happy new year :-)

I get this error

>DataError: invalid input syntax for integer: "{}"
>LINE 1: ...el (partner_id,category_id) values (4987, ARRAY[6, 0, '{}'])

when i try to create a new customer with attribute for tags :
 > :category_id => [1],
                   
This field is not mandatory, but cause an error if missing (strange behaviour of odoo...). And setting  parameter create error too. Any tips or workaround please ?

Thanks for all.

Regards

**Comment by tboulogne** [comment]
[UPDATE]

seem to works with 
> cu = ResPartner.new(:name => "toto", :category_id => [1])
>cu.save

and not
> cu = ResPartner.new(:name => "toto", :category_id => [1])
>cu.create

**Comment by azurewraith** [comment]
I run into this a lot...
