### ISSUE TITLE
Odoo 8 : Session expired

### ISSUE THREAD

**Issue by tboulogne** [akretion/ooor#123]
Hello,

After a code update of odoo 8 after a security advisory, i could not connect with ooor. i get the message :
> : session for uid: 1 has expired, trying to login again

Printing traceback, i get the error below.

```
#####OPE Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 532, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 160, in _dispatch
    auth_method = self._authenticate(func.routing["auth"])
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 93, in _authenticate
    getattr(self, "_auth_method_%s" % auth_method)()
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 70, in _auth_method_user
    raise http.SessionExpiredException("Session expired")
SessionExpiredException: Session expired
```

Any idea to solve this please ?

Thanks for help.

regards,

**Comment by tboulogne** [comment]
Hello,

Any help on this ? Thanks for your precious reply.... a dozen of scripts are frozen now :-(

**Comment by azurewraith** [comment]
I'm running into this same issue now... any suggestions @rvalyi?

**Comment by azurewraith** [comment]
It appears as though this was fixed: https://github.com/odoo/odoo/commit/96135fa7855ce22fd2ce7c7f0d59f99800216a50

For whatever reason my code has no `rotate` attribute so I think I have the wrong release.

**Comment by tboulogne** [comment]
thanks for the update.

Le 28/08/2015 18:10, azurewraith a écrit :
>
> I'm running into this same issue now... any suggestions @rvalyi 
> <https://github.com/rvalyi>?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/akretion/ooor/issues/123#issuecomment-135820928>.
>

--
