### ISSUE TITLE
Multithreading Problem?

### ISSUE THREAD

**Issue by solars** [akretion/ooor#127]
Hi there,

I've got a rails application that uses 2 different ooor calls:

Call A returns a String like askdfj-23423-lkj
Call B returns a decimal like 5.2

I now had the scenario that Call B received a response that typically only call A gets and I did not understand why. However, I assume it is because we have 2 instances of this app running (2 passenger servers).

Can anyone tell me if there is a way to prevent this?

Thanks a lot,
Christoph

**Comment by solars** [comment]
Can anyone help me please?

**Comment by rvalyi** [comment]
sorry for the delay, 2015 was a bad year for me, it's better now. Likely fixed by https://github.com/akretion/ooor/issues/91
Please re-open if not.

**Comment by solars** [comment]
@rvalyi thanks a lot! I've sent you an email regarding this issue (as we were incontact before about it) could you maybe have a look?

**Comment by rvalyi** [comment]
@solars oh yes sorry, I didn't relate your username with your name. So it's fixed indeed.

**Comment by solars** [comment]
@rvalyi there was a problem when I tried it, see reply to your email requesting me to test it "OOOR and HTTPS"

**Comment by solars** [comment]
Hi Raphael,

A quick question regarding OOOR - I noticed it is not Rails5 compatible,
and since there were not too many commits in the last year
I kindly wanted to ask if there are plans to upgrade to it? I tried myself
but the project is rather complex,

I'm wondering because we are switching our applications to Rails5 and it
might be easier to switch to OpenERP REST endpoints instead.

Thank you,
Christoph

**Comment by rvalyi** [comment]
@solars Rails 5 compat will soon be fixed https://github.com/akretion/ooor/pull/153
Also a few more commits and Rails usage documentation coming soon, stay tuned.

**Comment by solars** [comment]
@rvalyi great to hear, thank you!

**Comment by solars** [comment]
Hi Raphael,

Any news about Rails 5 support?

Thank you,
Christoph
