### ISSUE TITLE
UML class exist? print_uml work?

### ISSUE THREAD

**Issue by flyfy1** [akretion/ooor#138]
Following the Wiki from here: <https://github.com/akretion/ooor/wiki/drawing-openerp-uml-diagrams-with-ooor>

It seems to me that I can print UML.. however, there's no such method called `print_uml`, when I was trying to do: `SaleOrder.print_uml`; additionally, the class `UML` doesn't seem to exist.

I even searched through the code base of ooor, but I cannot find anywhere `UML` class defined.

Any idea?

**Comment by hugosantosred** [comment]
@flyfy1 print_uml method has moved to another gem, this is the commit where print_uml method dissapeared from ooor: https://github.com/akretion/ooor/commit/5d39e2a8f500d508efbb6769fde8a0779139dfe9

Now you can find this method in [ooor-doc](https://github.com/akretion/ooor-doc) gem 

https://github.com/akretion/ooor-doc/blob/master/lib/ooor-doc/uml.rb

**Comment by flyfy1** [comment]
Thanks :)
