### ISSUE TITLE
ooor.yml?

### ISSUE THREAD

**Issue by flyfy1** [akretion/ooor#139]
In the wiki: <https://github.com/akretion/ooor/wiki/using-Ooor-in-Rails-applications>

It says `ooor.yml` file exist in the repo, and in order for me to integrate Rails with OOOR, I need to use that `ooor.yml` as a template file.

However, I cannot find that `ooor.yml` file.. could anyone provide any link?

PS: the link for `ooor.yml` in the wiki has broken.

**Comment by rvalyi** [comment]
@flyfy1 sorry for the delay and the doc discrepancy. You can read ooorest doc for a Rails usage:
https://github.com/akretion/ooorest
you alsohave an example of ooor.yml in this sample app:
https://github.com/akretion/ooorest-app/blob/master/config/ooor.yml

FYI I'm actually working again on integration Odoo and LocomotiveCMS using ooor. I should push some stuff soon, so I'm working on the topic these days...

**Comment by flyfy1** [comment]
Thanks
