### ISSUE TITLE
Rails 5 error

### ISSUE THREAD

**Issue by sebastienbeau** [akretion/ooor#150]
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'ooorest'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant ActiveModel::Serializers::Xml
Backtrace for gem load error is:
/usr/local/bundle/bundler/gems/ooor-a7789e76d73e/lib/ooor/mini_active_resource.rb:67:in `<class:MiniActiveResource>'
/usr/local/bundle/bundler/gems/ooor-a7789e76d73e/lib/ooor/mini_active_resource.rb:13:in `<module:Ooor>'
/usr/local/bundle/bundler/gems/ooor-a7789e76d73e/lib/ooor/mini_active_resource.rb:5:in `<top (required)>'
/usr/local/bundle/bundler/gems/ooor-a7789e76d73e/lib/ooor/base.rb:16:in `require'
/usr/local/bundle/bundler/gems/ooor-a7789e76d73e/lib/ooor/base.rb:16:in `<module:Ooor>'
/usr/local/bundle/bundler/gems/ooor-a7789e76d73e/lib/ooor/base.rb:13:in `<top (required)>'
/usr/local/bundle/bundler/gems/ooorest-01527b455c50/lib/ooorest/action_window_controller.rb:3:in `require'
/usr/local/bundle/bundler/gems/ooorest-01527b455c50/lib/ooorest/action_window_controller.rb:3:in `<top (required)>'
/usr/local/bundle/bundler/gems/ooorest-01527b455c50/lib/ooorest.rb:3:in `require'
/usr/local/bundle/bundler/gems/ooorest-01527b455c50/lib/ooorest.rb:3:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
/workspace/config/application.rb:7:in `<top (required)>'
/usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:88:in `require'
/usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
/usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
/usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
/usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
/usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
/workspace/bin/rails:9:in `require'
/workspace/bin/rails:9:in `<top (required)>'
/usr/local/bundle/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
/usr/local/bundle/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
/usr/local/bundle/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
/usr/local/bundle/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
/usr/local/bundle/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
/usr/local/bundle/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
/usr/local/bundle/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
/workspace/bin/spring:14:in `require'
/workspace/bin/spring:14:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

We need to add some new dependency for rails 5

https://github.com/rails/rails/issues/24558

**Comment by solars** [comment]
Is there still no rails 5 support?

**Comment by DamienMetzger** [comment]
Small progress here, I now have a new error `cannot load such file -- active_model_serializers` when I use `Ooor.new`
Other libs suggest to add `gem 'activemodel-serializers-xml', github: 'rails/activemodel-serializers-xml'` to the Gemfile, but there is no improvement for me...

**Comment by rvalyi** [comment]
fixed by https://github.com/akretion/ooor/commit/0ffec7f417a5a9c2b8db7fc60644742a4a082543
sorry for the delay
