### ISSUE TITLE
Rails 5 compatibility?

### ISSUE THREAD

**Issue by solars** [akretion/ooor#152]
Hi there,

I wanted to upgrade one of our projects to Rails 5 and came across this error:

gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/stack.rb:112:in `assert_index': No such middleware to insert after: ActionDispatch::ParamsParser (RuntimeError)

It seems to be caused by ooor (github version):
lib/ooor/railtie.rb:        app.middleware.insert_after ActionDispatch::ParamsParser, '::Ooor::Rack'

Is it possible for me to fix/change this somehow? I'm not very familiar with that particular code.

Thank you

**Comment by solars** [comment]
Reason is that ActionDispatch::ParamsParser is removed with Rails 5, thus cannot insert_after

**Comment by solars** [comment]
Is OOOR still not rails 5 compatible?

**Comment by augustosamame** [comment]
+1

**Comment by rvalyi** [comment]
OK I just fixed a Rails5 issue here https://github.com/akretion/ooor/commit/0ffec7f417a5a9c2b8db7fc60644742a4a082543 and I'll fix this middleware issue next

**Comment by rvalyi** [comment]
it seems this problem happens in Rails 5.1 but not in Rails 5.0. I'm on it still...

**Comment by rvalyi** [comment]
I was wrong, the bug happens on Rails 5.0 too. Still thinking were to install the ooor middleware... For the record, on Raisl 5.1 the middleware stack looks like:
```
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use ActionDispatch::RemoteIp
use Sprockets::Rails::QuietAssets
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use WebConsole::Middleware
use ActionDispatch::DebugExceptions
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
```

**Comment by rvalyi** [comment]
fixed via https://github.com/akretion/ooor/commit/3d6825a3e29e128a3282f12a52342fca5fd1fb11
compatibility with Rails 4 middleware stack is retained.
