### ISSUE TITLE
NameError: uninitialized constant ActiveSupport::Notifications

### ISSUE THREAD

**Issue by oscarsan** [akretion/ooor#154]
Hi

Im getting an erro when logging in using ooor, by IRB or using the actual embedded binary, it seems to be something with ActiveSupport, I have install the newest odoo as today from github, not sure if that maybe the problem
```
NameError: uninitialized constant ActiveSupport::Notifications
	from /Users/oscar/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.1/lib/active_support/cache.rb:562:in `instrument'
	from /Users/oscar/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.1/lib/active_support/cache.rb:396:in `write'
	from /Users/oscar/.rvm/gems/ruby-2.2.2/gems/ooor-2.4.0/lib/ooor/session_handler.rb:53:in `set_web_session'
	from /Users/oscar/.rvm/gems/ruby-2.2.2/gems/ooor-2.4.0/lib/ooor/session_handler.rb:39:in `register_session'
	from /Users/oscar/.rvm/gems/ruby-2.2.2/gems/ooor-2.4.0/lib/ooor/services.rb:59:in `login'
	from /Users/oscar/.rvm/gems/ruby-2.2.2/gems/ooor-2.4.0/lib/ooor/services.rb:101:in `object_service'
	from /Users/oscar/.rvm/gems/ruby-2.2.2/gems/ooor-2.4.0/lib/ooor/session.rb:98:in `read_model_data'
	from /Users/oscar/.rvm/gems/ruby-2.2.2/gems/ooor-2.4.0/lib/ooor/session.rb:84:in `load_models'
	from /Users/oscar/.rvm/gems/ruby-2.2.2/gems/ooor-2.4.0/lib/ooor/session.rb:47:in `global_login'
	from /Users/oscar/.rvm/gems/ruby-2.2.2/gems/ooor-2.4.0/lib/ooor.rb:64:in `new'
	from (irb):2
	from /Users/oscar/.rvm/rubies/ruby-2.2.2/bin/irb:11:in `<main>'
```

ooor version is 2.4.0
ruby 2.2.0
odoo 
```
{"server_serie"=>"10.0", "server_version_info"=>[10, 0, 0, "final", 0, ""], "server_version"=>"10.0", "protocol_version"=>1}
```

**Comment by DamienMetzger** [comment]
Same here !

**Comment by rvalyi** [comment]
it's because ooor is not yet Rails 5 compatible. It should be quite straightforward.
I should try this PR https://github.com/akretion/ooor/pull/153/files
that would be cool if you could test it and confirm it works.

**Comment by DamienMetzger** [comment]
I have not idea how to do that ^^
My best try (cloning the PR, `gem build ooor.gemspec` then `gem install ooor-2.3.0.gem` ended in a nice segfault when executing bin/ooor

**Comment by sebastienbeau** [comment]
Hi @DamienMetzger sorry to respond so late
If you want to test the gem in your project you can just add the following line into you Gemfile

gem 'ooor', git: "https://github.com/akretion/ooor.git", branch: "rails5"

Then if you run bundle install it will install this specific version of the gem

**Comment by rvalyi** [comment]
can you test again with HEAD? I just fixed Rails 5 compatibility here https://github.com/akretion/ooor/commit/0ffec7f417a5a9c2b8db7fc60644742a4a082543 and tests are now passing
