### ISSUE TITLE
Scope prefix and undefined model

### ISSUE THREAD

**Issue by hachpai** [akretion/ooor#156]
Hello,

When I don't define a scope prefix to namespace my models, the ooor registered models are all available.
If I try to prefix by adding that line to my default config in ooor.yml:
````
default: &default
  #scope_prefix: 'ERP1'
````
My ooor models are no more available anywhere (as 'ERP1::ResPartner') when I run `rails s`.
With an IRB and `rails c`, everything works fine with the same code. Models are well referenced as 'ERP1::ResPartner'.

Any idea to solve that? What makes a difference between server and console for model registration?

Thank you

WPH

**Comment by rvalyi** [comment]
with the new session system I'going to deprecate the scope system to leave the code simpler. So if there is a bug here it will not be fixed. You better use different ooor sessions if you want to connect to different databases or Odoo systems (if the reason for using scope was only to avoid class name collision, the session system will also do it as it doesn't generate class names automatically anymore, it only generate them when using ooor from command line). When creating an ooor session, you can set ```:generate_constants``` to true or false to generate constants or not.
