### ISSUE TITLE
Endless loop with new object form through OooREST [SystemStackError in Crm_case#new]

### ISSUE THREAD

**Issue by matdie** [akretion/ooor#40]
Hi Raphaël,

I get the following error when I try to open a form for a new `crm_case` object using OooREST (`http://localhost:3000/crm_case/new`):

    D:/Ruby/lib/ruby/gems/1.9.1/gems/ooor-1.3.2/lib/app/models/open_object_resource.rb:455:in `block in method_missing'
    D:/Ruby/lib/ruby/gems/1.9.1/gems/ooor-1.3.2/lib/app/models/open_object_resource.rb:454:in `each'
    D:/Ruby/lib/ruby/gems/1.9.1/gems/ooor-1.3.2/lib/app/models/open_object_resource.rb:454:in `method_missing'
    D:/Ruby/lib/ruby/gems/1.9.1/gems/ooor-1.3.2/lib/app/models/open_object_resource.rb:56:in `block (3 levels) in reload_fields_definition'
    -- snipped --
    D:/Ruby/lib/ruby/gems/1.9.1/gems/ooor-1.3.2/lib/app/models/open_object_resource.rb:471:in `method_missing'
    D:/Ruby/lib/ruby/gems/1.9.1/gems/ooor-1.3.2/lib/app/models/open_object_resource.rb:56:in `block (3 levels) in reload_fields_definition'
    D:/Ruby/lib/ruby/gems/1.9.1/gems/activeresource-2.3.5/lib/active_resource/base.rb:775:in `new?'
    D:/Ruby/lib/ruby/gems/1.9.1/gems/actionpack-2.3.5/lib/action_view/helpers/form_helper.rb:290:in `apply_form_for_options!'
    D:/Ruby/lib/ruby/gems/1.9.1/gems/actionpack-2.3.5/lib/action_view/helpers/form_helper.rb:277:in `form_for'

Contents of `new.html.erb`:

    <h2>New Case</h2>
    <% form_for(@models) do |f| %>
        <p>
            <%= f.label :code %><br />
            <%= f.text_field :code %>
        </p>
    <% end %>

I'm following the Rails guide, so it may be that I haven't set this up properly to work with OooREST.

**Comment by rvalyi** [comment]
this should be fixed these days
