### ISSUE TITLE
Ooor.new crashes on loading models

### ISSUE THREAD

**Issue by Kelbethor** [akretion/ooor#58]
I, [2011-02-11T02:43:31.070083 #7080]  INFO -- : registering IrModel as an ActiveResource proxy for OpenObject ir.model model
D, [2011-02-11T02:43:31.070083 #7080] DEBUG -- : OOOR RPC: rpc_method: 'execute', db: dbname, uid: 1, pass: #, obj: ir.model, method: fields_get, *args
: []
Timeout::Error: Timeout::Error
        from C:/Ruby192/lib/ruby/1.9.1/net/protocol.rb:140:in `rescue in rbuf_fill'
        from C:/Ruby192/lib/ruby/1.9.1/net/protocol.rb:134:in `rbuf_fill'
        from C:/Ruby192/lib/ruby/1.9.1/net/protocol.rb:116:in `readuntil'
        from C:/Ruby192/lib/ruby/1.9.1/net/protocol.rb:126:in `readline'
        from C:/Ruby192/lib/ruby/1.9.1/net/http.rb:2211:in `read_status_line'
        from C:/Ruby192/lib/ruby/1.9.1/net/http.rb:2200:in `read_new'
        from C:/Ruby192/lib/ruby/1.9.1/net/http.rb:1183:in `transport_request'
        from C:/Ruby192/lib/ruby/1.9.1/net/http.rb:1169:in `request'
        from C:/Ruby192/lib/ruby/1.9.1/net/http.rb:1117:in `request_post'
        from C:/Ruby192/lib/ruby/1.9.1/xmlrpc/client.rb:538:in `do_rpc'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/ooor-1.4.2/lib/app/models/ooor_client.rb:24:in `call2'
        from C:/Ruby192/lib/ruby/1.9.1/xmlrpc/client.rb:410:in `call'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/ooor-1.4.2/lib/app/models/open_object_resource.rb:135:in `rpc_execute_with_all'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/ooor-1.4.2/lib/app/models/open_object_resource.rb:127:in `rpc_execute_with_object'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/ooor-1.4.2/lib/app/models/open_object_resource.rb:123:in `rpc_execute'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/ooor-1.4.2/lib/app/models/open_object_resource.rb:61:in `reload_fields_definition'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/ooor-1.4.2/lib/app/models/open_object_resource.rb:133:in `rpc_execute_with_all'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/ooor-1.4.2/lib/app/models/open_object_resource.rb:127:in `rpc_execute_with_object'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/ooor-1.4.2/lib/app/models/open_object_resource.rb:123:in `rpc_execute'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/ooor-1.4.2/lib/app/models/open_object_resource.rb:106:in `search'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/ooor-1.4.2/lib/ooor.rb:75:in `load_models'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/ooor-1.4.2/lib/ooor.rb:61:in `initialize'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/ooor-1.4.2/lib/ooor.rb:28:in `new'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/ooor-1.4.2/lib/ooor.rb:28:in `new'
        from (irb):3
        from C:/Ruby192/bin/irb:12:in `<main>'irb(main):004:0>

**Comment by rvalyi** [comment]
should be fixed. Re-open if it happens again on master
