### ISSUE TITLE
How to use the ooor command or run it

### ISSUE THREAD

**Issue by vardhan-nyros** [akretion/ooor#99]
Hi,

I am a ROR developer and installed the  gem ooor but I am not clear in how to get it work.

After installing I run the command "ooor username.database@host:xmlrpc_port", it throws me error can you please specify which DB it is using and how to integrate it to a rails app and can we change the Database to Postgres/MySql

**Comment by rvalyi** [comment]
closing as it was a request for support rather than a bug. I'm still improving the doc...
